export const CMSPatterns = {
  HEALTH: 'cms.health',
  SOURCE_UPLOAD: 'cms.source.upload',
  SOURCE_FROM_URL: 'cms.source.from_url',
  SOURCE_FIND: 'cms.source.find',
  SOURCE_DELETE: 'cms.source.delete',
  SOURCE_UPDATE_NAME: 'cms.source.setName',
  MEDIA_ALL: 'cms.media.all',
  MEDIA_FIND: 'cms.media.find',
  MEDIA_NEW: 'cms.media.create',
  MEDIA_UPDATE: 'cms.media.update',
  MEDIA_PUBLISH: 'cms.media.publish',
  MEDIA_DISCARD: 'cms.media.discard',
  MEDIA_METADATA: 'cms.media.metadata',
  MEDIA_METADATA_UPDATE: 'cms.media.metadata.update',
} as const;
